# 100 numpy exercises

https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Print the numpy version and the configuration

In [2]:
print(np.__version__)
print(np.show_config())

1.22.3
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

3. Create a null vector of size 10

In [3]:
vector = np.zeros(10)

4. How to find the memory size of any array

In [4]:
np.array(vector).nbytes

80

5. How to get the documentation of the numpy add function from the command line? 

In [6]:
np.add?

6. Create a null vector of size 10 but the fifth value which is 1

In [9]:
A = np.zeros(10)
A[4] = 1
A

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49

In [10]:
B = np.arange(10, 50)
B

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last)

In [11]:
np.flip(B)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

9. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [15]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

11. Create a 3x3 identity matrix 

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

12. Create a 3x3x3 array with random values

In [17]:
np.random.random(size=(3,3,3))

array([[[0.6026994 , 0.85576784, 0.35949705],
        [0.74798104, 0.08194059, 0.8416766 ],
        [0.23967625, 0.92791052, 0.2817512 ]],

       [[0.55557941, 0.82502292, 0.83472084],
        [0.75693024, 0.52608599, 0.94117347],
        [0.24565688, 0.35686899, 0.00271938]],

       [[0.70827553, 0.37377823, 0.20521781],
        [0.19462671, 0.74943801, 0.21021951],
        [0.76604078, 0.95722376, 0.62437507]]])

13. Create a 10x10 array with random values and find the minimum and maximum values

In [19]:
A = np.random.random(size=(10,10))
print(A)
print(A.min())
print(A.max())

[[0.31716362 0.61009558 0.50685178 0.7167135  0.75080085 0.27898473
  0.09694978 0.91756778 0.09438094 0.58924675]
 [0.91340411 0.58142219 0.95626456 0.37632954 0.15041578 0.91992819
  0.52816021 0.04774762 0.57070371 0.52106484]
 [0.37218043 0.30625001 0.87767294 0.65008456 0.06674757 0.67407664
  0.59328584 0.89873525 0.87979976 0.23712366]
 [0.54283397 0.14616626 0.53005152 0.69061697 0.97389979 0.18741892
  0.30530729 0.70039347 0.84800772 0.63614136]
 [0.58288272 0.23114536 0.15375581 0.12582062 0.12365492 0.97162919
  0.66490882 0.41730549 0.31479825 0.96302895]
 [0.69489335 0.88275436 0.7002818  0.63490754 0.98162588 0.34174505
  0.55271042 0.56848402 0.84378101 0.36671725]
 [0.87583675 0.70425166 0.38817504 0.35142    0.40499956 0.73290901
  0.30407903 0.9238985  0.80607851 0.55027593]
 [0.16936821 0.23849423 0.86318537 0.79974659 0.30371266 0.86514459
  0.18067265 0.78439195 0.87973257 0.87821813]
 [0.50420812 0.14383204 0.91802935 0.34872513 0.46556146 0.96960245
  0.65521804

14. Create a random vector of size 30 and find the mean value

In [20]:
A = np.random.random(10)
print(A.mean())

0.5516460246224839


15. Create a 2d array with 1 on the border and 0 inside

In [22]:
A = np.ones((5,5))
A[1:-1,1:-1] = 0
print(A)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array?

In [23]:
A = np.ones((5,5))
print(np.pad(A, pad_width=1))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17. What is the result of the following expression?
0 * np.nan               nan
np.nan == np.nan         False
np.inf > np.nan          False
np.nan - np.nan          nan
np.nan in set([np.nan])  True
0.3 == 3 * 0.1           False

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [35]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [49]:
A = np.zeros((8, 8),dtype=int)
A[1::2,::2] = 1
A[::2,1::2] = 1
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [55]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


21. Create a checkerboard 8x8 matrix using the tile function

In [58]:
A = np.tile([[1,0], [0,1]],(4,4))
print(A)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


22. Normalize a 5x5 random matrix

In [59]:
A = np.random.random((5,5))
A = (A - np.mean(A) / (np.std(A)))
print(A)

[[-1.45383117 -1.52456673 -1.50262794 -1.56876844 -1.81021867]
 [-1.5175762  -1.35870382 -1.00057573 -1.38726267 -1.70170691]
 [-1.79399688 -1.54006779 -1.35055382 -1.07753738 -1.11706686]
 [-1.11016829 -1.41165856 -1.7051599  -1.87501233 -1.22115127]
 [-1.14627358 -1.38415994 -1.48953173 -0.98411142 -1.19411565]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [60]:
dt = np.dtype([('R','u1'), ('G','u1'), ('B','u1'), ('A','u1')])

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [61]:
A = np.random.random((5,3))
B = np.random.random((3,2))
print(A.dot(B))

[[0.86481877 1.01820897]
 [0.60900274 0.75855614]
 [0.87349025 1.01058893]
 [0.61658988 0.74303686]
 [0.42034216 0.46493149]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [66]:
X = np.arange(10)
X[3:9] *= -1
print(X)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


26. What is the output of the following script?

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [67]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal?
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [69]:
Z = np.arange(10)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

In [70]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-70-cd809174da5d>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-70-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

29. How to round away from zero a float array ? 

In [71]:
Z = np.random.uniform(-10,+10,10)
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 4.  3. -5.  4. 10.  7. -6. 10.  9. -9.]


30. How to find common values between two arrays?

In [72]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8])
B = np.array([2, 4, 6, 8, 10, 12, 14, 16])
print(np.intersect1d(A,B))

[2 4 6 8]


31. How to ignore all numpy warnings (not recommended)? 

In [74]:
defaults = np.seterr(all="ignore")
_ = np.seterr(**defaults)

32. Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)
No

In [75]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

33. How to get the dates of yesterday, today and tomorrow?

In [4]:
print(np.datetime64('today') - np.timedelta64(1, 'D'))
print(np.datetime64('today'))
print(np.datetime64('today') + np.timedelta64(1, 'D'))

2022-07-01
2022-07-02
2022-07-03


34. How to get all the dates corresponding to the month of July 2016?

In [7]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [10]:
A = np.ones(3)*1
B = np.ones(3)*2
print(np.multiply(np.add(A,B),np.divide(np.negative(A),2)))

[-1.5 -1.5 -1.5]


In [11]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

36. Extract the integer part of a random array of positive numbers using 4 different methods

In [23]:
A = np.random.random(10)*50
print(A)
print(np.rint(A))
print(np.around(A,0))
print(np.int8(A))
print(A.astype(int))

[21.15425007 43.27604121 20.994922   40.12818247 18.26603232  9.77147573
 23.09748193  0.83451898 19.6953394  44.36919599]
[21. 43. 21. 40. 18. 10. 23.  1. 20. 44.]
[21. 43. 21. 40. 18. 10. 23.  1. 20. 44.]
[21 43 20 40 18  9 23  0 19 44]
[21 43 20 40 18  9 23  0 19 44]


37. Create a 5x5 matrix with row values ranging from 0 to 4

In [29]:
np.tile(np.arange(5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

38. Consider a generator function that generates 10 integers and use it to build an array

In [34]:
iterable = (x for x in range(10))
np.fromiter(iterable, int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

39. Create a vector of size 10 with values ranging from 0 to 1, both excluded 

In [40]:
x = np.linspace(0, 1, 11, False)
print(x[1:])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. Create a random vector of size 10 and sort it 

In [48]:
A = np.random.random(10) * 10
np.sort(A)

array([1.98586319, 2.29890748, 3.98016135, 4.13185446, 4.22730716,
       4.63159344, 6.36767142, 8.02748863, 8.57638785, 9.52477446])

41. How to sum a small array faster than np.sum? 

In [49]:
A = np.random.random(10) * 10
np.add.reduce(A)

55.46596512844612

42. Consider two random array A and B, check if they are equal

In [50]:
A = np.random.random(10) * 10
B = np.random.random(10) * 10
print(np.array_equal(A,B))

False


43. Make an array immutable (read-only)

In [52]:
A = np.random.random(10) * 10
A.flags["WRITEABLE"] = False

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [56]:
C = (np.random.random((10,2)) * 10).astype(int)
print(C)
X, Y = C[:,0], C[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
P = np.zeros((10,2))
P[:,0], P[:,1] = R, T
print(P)

[[7 0]
 [8 1]
 [8 9]
 [1 5]
 [6 3]
 [5 1]
 [2 0]
 [9 6]
 [6 1]
 [1 7]]
[[ 7.          0.        ]
 [ 8.06225775  0.12435499]
 [12.04159458  0.84415399]
 [ 5.09901951  1.37340077]
 [ 6.70820393  0.46364761]
 [ 5.09901951  0.19739556]
 [ 2.          0.        ]
 [10.81665383  0.5880026 ]
 [ 6.08276253  0.16514868]
 [ 7.07106781  1.42889927]]


45. Create random vector of size 10 and replace the maximum value by 0

In [63]:
A = np.random.random(10) * 10
print(A)
A[np.argmax(A)] = 0
print(A)

[9.92843309 9.49185257 6.63816353 7.1771728  2.65371307 5.92822635
 2.80498027 2.8862341  4.1512915  7.53384647]
[0.         9.49185257 6.63816353 7.1771728  2.65371307 5.92822635
 2.80498027 2.8862341  4.1512915  7.53384647]


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [65]:
nx = [0, 1]
ny = [0, 1]
x, y = np.meshgrid(nx, ny)
print(x)
print(y)

[[0 1]
 [0 1]]
[[0 0]
 [1 1]]


47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [2]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


48. Print the minimum and maximum representable value for each numpy scalar type

In [10]:
print(np.iinfo(np.int8).min)
print(np.iinfo(np.int8).max)
print(np.iinfo(np.int16).min)
print(np.iinfo(np.int16).max)
print(np.iinfo(np.int32).min)
print(np.iinfo(np.int32).max)
print(np.iinfo(np.int64).min)
print(np.iinfo(np.int64).max)
print(np.finfo(np.float32).min)
print(np.finfo(np.float32).max)
print(np.finfo(np.float64).min)
print(np.finfo(np.float64).max)

-128
127
-32768
32767
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


49. How to print all the values of an array?

In [14]:
Z = np.zeros((10,10))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


50. How to find the closest value (to a given scalar) in a vector?

In [22]:
A = np.random.random(10) * 50
s = 10
print(A)
print(A[A > s])
print(A[np.argmin(A[A > s])])

[18.62025159  7.5003211  23.2596076  20.86947469  5.03115334 40.34283556
  2.55098436 20.5556318  38.42770677  4.35603008]
[18.62025159 23.2596076  20.86947469 40.34283556 20.5556318  38.42770677]
18.620251593810323
